### ISSUE TITLE
源码几乎与 madrobby/keymaster 完全相同

### ISSUE THREAD

**Issue by lmk123** [jaywcjlove/hotkeys#1]
Hi，我无意中看到你的这个项目，发现[你的源码](https://github.com/jaywcjlove/hotkeys/blob/master/src/hotkeys.js)与 [madrobby/keymaster](https://github.com/madrobby/keymaster) 的[源码](https://github.com/madrobby/keymaster/blob/master/keymaster.js)**相似度接近 96%**（包括变量名、函数名以及源码内容），仅有三点不同：

 + 给 Arrary.prototype.indexOf 方法打了个补丁
 + 注释改成了中文
 + 增加了 UMD 模式

我并没有“路见不平一声吼”的意思，只是想提醒一下，你可以 fork 一下源项目，再在你自己 fork 的项目里做修改，或者在 README.md 里说明一下借鉴了 madrobby/keymaster 的代码，这是出于对原作者的尊重 :)

你可以觉得我是多管闲事并关闭或修改掉这个 issue，谢谢 :)

**Comment by jaywcjlove** [comment]
@lmk123 嗯临摹大师的作品 REAME.md 里面我会加上的。谢谢提醒。
