### ISSUE TITLE
建议scope接受Symbol

### ISSUE THREAD

**Issue by luzhiy123** [jaywcjlove/hotkeys#102]
现有场景，在一个页面中不同组件绑定相同快捷键的情况下使用不同字符串scope区分了，但是使用同一个组件的情况下，需要自己做随机字符串或者去外部管理，

**Comment by jaywcjlove** [comment]
@luzhiy123 这个库是兼容低级浏览器，可能会引起不兼容问题。不过你可以提 RP 看看

**Comment by luzhiy123** [comment]
好的，我看看

**Comment by luzhiy123** [comment]
> @luzhiy123 这个库是兼容低级浏览器，可能会引起不兼容问题。不过你可以提 RP 看看

我看了下，直接传option 传 {scope: Symbol}能正常使用，只有直接传Symbol有问题，只判断了string 没有判断Symbol
