### ISSUE TITLE
Can't bind to + (plus)

### ISSUE THREAD

**Issue by madfriend** [jaywcjlove/hotkeys#104]
Hi!

The following example does not work:

```js
hotkeys("+", {}, () => console.log("pressed plus"));
```

That's because keys are [splitted by "+"](https://github.com/jaywcjlove/hotkeys/blob/master/src/main.js#L106). Can we have an option to specify a different splitter? E. g.

```
hotkeys("+", { splitKeysBy: "_" }, () => console.log("pressed plus"));
```

**Comment by jaywcjlove** [comment]
@madfriend  This is a good idea.

**Comment by madfriend** [comment]
Can we have a next minor release (3.6.15) with this feature?
