### ISSUE TITLE
input 设置 非输入框如：checkbox 、radio 、button等情况下快捷键也不生效

### ISSUE THREAD

**Issue by luzhiy123** [jaywcjlove/hotkeys#107]
https://github.com/jaywcjlove/hotkeys/issues/6

**Comment by jaywcjlove** [comment]
什么意思？ @luzhiy123 你是想输入框下可以使用快捷键？

**Comment by luzhiy123** [comment]
> 什么意思？ @luzhiy123 你是想输入框下可以使用快捷键？

input 不是输入框的时候支持，即单选多选和按钮等的时候

**Comment by luzhiy123** [comment]
@jaywcjlove 现在情况是单选多选框 的时候快捷键就因为filter 中判断的tagName导致失效

**Comment by jaywcjlove** [comment]
@luzhiy123 这里有个实例 https://codepen.io/jaywcjlove/pen/rNByvmP?editors=1011

添加一些判断就可以了。

```js
hotkeys.filter = ({ target }) => {
  return !(target.tagName === 'INPUT' && target.type !== 'radio') ;
}

hotkeys('ctrl+a,command+a', function(event,handler) {
  event.preventDefault();
  console.log('handle~~~~', handler.key,  event)
});
```
