### ISSUE TITLE
怎么快捷的删除一个scope下所有绑定事件

### ISSUE THREAD

**Issue by luzhiy123** [jaywcjlove/hotkeys#112]
能否提供一个方法清除一个scope下所有绑定事件，之前误以为deleteScope做了这个工作

**Comment by jaywcjlove** [comment]
所有的快捷键事件都绑定到了 keydown 和 keyup 事件里面，你可以通过 `scope` 切换

**Comment by herrdu** [comment]
试一下    `hotkeys.unbind()`
