### ISSUE TITLE
Do not work for some keys

### ISSUE THREAD

**Issue by xcv58** [jaywcjlove/hotkeys#13]
The `ArrowUp`, `ArrowDown`, and `backsapce` don't work.
MacOS, Chrome Version 62.0.3202.9 (Official Build) dev (64-bit)

![image](https://user-images.githubusercontent.com/503123/30237314-51728112-94e4-11e7-8103-68e921971b37.png)
![image](https://user-images.githubusercontent.com/503123/30237317-6167ee04-94e4-11e7-8a70-965df8e2ff39.png)
![image](https://user-images.githubusercontent.com/503123/30237322-79d4b602-94e4-11e7-8ded-4b18c9238adc.png)

**Comment by jaywcjlove** [comment]
`ArrowUp` => `up`  
`ArrowDown` => `down`  
`ArrowLeft` => `left`
`ArrowRight` => `right`  


```js
hotkeys('up,down,left,right', function(e){
    // do someting
});
```

**Comment by xcv58** [comment]
Great thank you!
