### ISSUE TITLE
F5刷新tab页面跟浏览器的页面刷新冲突如何解决？

### ISSUE THREAD

**Issue by wulinjie122** [jaywcjlove/hotkeys#14]
项目中有这样一个需求，按F5刷新打开的tab页面，而不是整个浏览器都刷新，这种情况下如何解决浏览器默认的F5快捷键冲突？

**Comment by jaywcjlove** [comment]
@wulinjie122 无法帮助到你，你这个奇怪的需求，关键是我没有安装Windows虚拟机没有办法给你调试，我的是mac电脑。😆

不过应该有办法解决，因为苹果电脑上面 `command+r` 刷新，我都解决了。

应该可以解决，demo页面，你看能不能捕获F5，然后浏览器环境......

**Comment by wulinjie122** [comment]
找到了，用event.preventDefault()解决了，阻止了浏览器默认行为。

**Comment by jaywcjlove** [comment]
@wulinjie122  是这个呢`event.preventDefault()`，我以为是你的环境下监听不到F5这个键。

**Comment by wulinjie122** [comment]
没，只是暂时忘记了，突然想起来了，哈哈。
