### ISSUE TITLE
组合键bug？

### ISSUE THREAD

**Issue by yyman001** [jaywcjlove/hotkeys#18]
按住ctrl，+z，放开z，ctrl消失了。

**Comment by jaywcjlove** [comment]
@yyman001 你这个是新 feature。可以组合多个字母键，就像多个 修饰键组合一样

**Comment by zengxiaoluan** [comment]
@jaywcjlove I pressed `ctrl+shift+z` and `shift+ctrl+z`, how to deal this situation defferently, I tested it but they same.

**Comment by zengxiaoluan** [comment]
支持 `ctrl+a+ctrl+b` 这种组合键的方式吗？ @jaywcjlove

**Comment by jaywcjlove** [comment]
@zengxiaoluan 不支持

**Comment by jaywcjlove** [comment]
@zengxiaoluan 这个是正常的，把快捷键放 JSON 对象里面维护，而不是通过事件来维护快捷键的使用。

**Comment by zengxiaoluan** [comment]
> 支持 `ctrl+a+ctrl+b` 这种组合键的方式吗？ @jaywcjlove
> 
> I looked around the source code and found the `_downKeys` never cleared out, does it normal?

@jaywcjlove 我觉得我们应该实现这个特性，不知道你有没有什么好的思路，我来贡献代码。

**Comment by jaywcjlove** [comment]
你是摁两遍还是 `ctrl+a+b` ? @zengxiaoluan

**Comment by zengxiaoluan** [comment]
> 你是摁两遍还是 `ctrl+a+b` ? @jaywcjlove 

最好两种都需要，就像 vs code `ctrl+k+ctrl+0` 是收缩全部代码一样。

**Comment by jaywcjlove** [comment]
你说的这种是类快捷键组合 `ctrl+k` + `ctrl+0` 你可以尝试下面这种思路

```js
const keys = [];
hotkeys('ctrl+a,ctrl+b', function(event, handler) {
  // 记录摁键
  keys.unshift(handler.key);

  if(handler.key === 'ctrl+b' && keys[0] === 'ctrl+a') {
    // 这里干活
  }
});
```

这个想法倒是可以集成到 `hotkeys` 里面。

**Comment by jaywcjlove** [comment]
现在已经，支持多键组合请查看 #55 ，支持 `keyup` 和 `keydown ` 事件模式查看 #57 

@zengxiaoluan @yyman001
