### ISSUE TITLE
Differences from mousetrap?

### ISSUE THREAD

**Issue by sloria** [jaywcjlove/hotkeys#21]
I see references to [Mousetrap](https://github.com/ccampbell/mousetrap) in the documentation, which leads me to believe this library was inspired by or adapted from it. Can you explain the differences between this library and Mousetrap?

**Comment by jaywcjlove** [comment]
@sloria There is no relationship with Mousetrap. I think the translation is more accurate and I read people's documents. This is a mistake and I will correct it.

**Comment by sloria** [comment]
Ah, ok. I'm still curious if there are differences in featureset or approach between hotkeys.js and Mousetrap.
