### ISSUE TITLE
What is scope?

### ISSUE THREAD

**Issue by stoplion** [jaywcjlove/hotkeys#214]
hotkeys.setScope('issues');

What is issues here? An element? An event type?

**Comment by jaywcjlove** [comment]
@stoplion Use the `hotkeys.setScope` method to set scope. There can only be one active scope besides 'all'. By default 'all' is always active.

```js

// Define shortcuts with a scope
hotkeys('ctrl+o, ctrl+alt+enter', 'issues', function(){
  console.log('do something');
});
hotkeys('o, enter', 'files', function(){ 
  console.log('do something else');
});

// Set the scope (only 'all' and 'issues' shortcuts will be honored)
hotkeys.setScope('issues'); // default scope is 'all'

```

**Comment by AndreyMiloserdov** [comment]
Make this code

// Define shortcuts with a scope
hotkeys('ctrl+o', {scope: 'issues'}, function(){
  console.log('[issues] ctrl+o');
});
hotkeys('ctrl+o', {scope: 'others'}, function(){
  console.log('[others] ctrl+o');
});
hotkeys.setScope('issues');

If press ctrl+o, there are will be "'[others] ctrl+o'" in console.
What i'm doing wrong?

**Comment by jaywcjlove** [comment]
@AndreyMiloserdov no problem. Example: https://codesandbox.io/s/hotkeys-214-r4u5p

**Comment by AndreyMiloserdov** [comment]
Thx!
