### ISSUE TITLE
The docs don't say that it's possible to unbind all.

### ISSUE THREAD

**Issue by cupcakearmy** [jaywcjlove/hotkeys#234]
Hi there :)

It would be very useful if the docs would mention that `unbind()` deletes all. Was looking for that functionality but had to look in to the source.

**Comment by jaywcjlove** [comment]
@cupcakearmy Wellcome to submit `PR`. thx!

**Comment by cupcakearmy** [comment]
@jaywcjlove  https://github.com/jaywcjlove/hotkeys/pull/235 there you go :)
