### ISSUE TITLE
isPressed 方法似乎状态没有清除

### ISSUE THREAD

**Issue by codertx** [jaywcjlove/hotkeys#24]
demo：https://jsfiddle.net/jjarx8za/

复现方法：
1.先随便按字母键，会看到按过的字母都会出现在#output元素里面
2.点击旁边的clean按钮，然后只按任意控制键，不按字母键。会发现之前按过的字母键又会出现在#output元素里面

不知道是不是真的是BUG还是设计如此？

**Comment by jaywcjlove** [comment]
@codertx 

Fork your demo: https://jsfiddle.net/jaywcjlove/v7mf856x/

<ruby>我觉得你的实现很奇怪。<rt>I think your implementation is very strange.</rt></ruby>

**Comment by codertx** [comment]
@jaywcjlove 
所以要判断当前是否按下了某个按键不能用 isPressed 么。。。

**Comment by jaywcjlove** [comment]
@codertx 这是一个bug

**Comment by jaywcjlove** [comment]
@codertx  https://jsfiddle.net/jaywcjlove/v7mf856x/2/


```html
<script src="https://unpkg.com/hotkeys-js@3.3.0/dist/hotkeys.min.js"></script>
```
