### ISSUE TITLE
How to draw the pic

### ISSUE THREAD

**Issue by Fun007fun** [jaywcjlove/hotkeys#250]
Could I ask a question that
how to draw <abbr title="the pic">this</abbr>

>╭┈┈╮          ╭┈┈╮  ╭┈┈╮
>┆  ├┈┈..┈┈┈┈┈.┆  └┈╮┆  ├┈┈..┈┈┈┈┈..┈┈.┈┈..┈┈┈┈┈.
>┆     ┆┆  □  ┆┆   ┈┤┆    < ┆  -__┘┆  ┆  ┆┆__ ┈┈┤
>╰┈┈┴┈┈╯╰┈┈┈┈┈╯╰┈┈┈┈╯╰┈┈┴┈┈╯╰┈┈┈┈┈╯╰┈┈┈  ┆╰┈┈┈┈┈╯
                                  ╰┈┈┈┈┈╯
Is there a software to make it?

**Comment by HarshitJoshi9152** [comment]
Although i am not sure how they made this art, In linux systems there is a command called banner which can be used to make big ASCII art versions on text.

**Comment by jaywcjlove** [comment]
Use Monodraw software.

![image](https://user-images.githubusercontent.com/1680273/124206391-d9cfc300-db15-11eb-9b53-05c295ab1c63.png)

![image](https://user-images.githubusercontent.com/1680273/124206424-ebb16600-db15-11eb-897e-7e00970261b1.png)


@Fun007fun @HarshitJoshi9152

**Comment by Fun007fun** [comment]
thank you!!
