### ISSUE TITLE
Not detecting state change

### ISSUE THREAD

**Issue by jellohouse** [jaywcjlove/hotkeys#264]
I have something like this:
```
const [num, setNum] =  useState(0);
...
useHotkeys('backspace, del, delete', () => {
    console.log("current state: ", num);
});
```

Whenever I change the `num` somewhere in my code like this: `setNum(3)`
when I press delete it still always says the initial state.

ie. `"current state: 0"`

**Comment by moklick** [comment]
You need to pass `num` in the dependency array like:

```js
const [num, setNum] =  useState(0);
...
useHotkeys('backspace, del, delete', () => {
    console.log("current state: ", num);
}, [num]);
```

It's documented here https://github.com/JohannesKlauss/react-hotkeys-hook#parameters (maybe better to use that repo when you have a question about one of the react packages)

**Comment by jellohouse** [comment]
Right!

Thank you so much this makes a lot of sense!
