### ISSUE TITLE
Modifier keys should be valid hotkeys

### ISSUE THREAD

**Issue by adamcbrewer** [jaywcjlove/hotkeys#27]
Currently it's not possible to use the modifier keys (shift, command, alt, etc.) on their own.

```js
hotkeys('shift+enter', () => {}); // works
// but...
hotkeys('shift', () => {}); // does not work
// similarly...
hotkeys('alt', () => {}); // does not work
hotkeys('cmd', () => {}); // does not work
```

Could this be added as a feature request or would you accept a pull-request with this functionality?

**Comment by jaywcjlove** [comment]
I accept this pull-request.

**Comment by adamcbrewer** [comment]
The issue is I don't want to bind to every key to just check for a single modifier. I think I'll try and find a similar library that supports modifiers on their own before submitting a pull request. Thanks!
