### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by jayliu50** [jaywcjlove/hotkeys#28]
hotkeys fails to initialize on IE11. `Error: Invalid calling object.`

This is caused by `hotkeys.common.js` line 333: `toString.call()` 

This is because `window.toString === Object.prototype.toString; // false`. See https://stackoverflow.com/questions/19321938/invalid-calling-object-error-in-ie?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Please use another way to test whether it's Object.

**Comment by jaywcjlove** [comment]
```js
var toString = function (x) { return ({}).toString.call(x); };
toString(10); // "[object Number]"
// or
var toString = ({}).toString.call.bind(({}).toString);
toString(true); // "[object Boolean]"
```
Compatible with IE8 +? @jayliu50

**Comment by jaywcjlove** [comment]
```
Object.prototype.toString.call({})
// => "[object Object]"
```
