### ISSUE TITLE
键盘放开的回调函数在那里设置

### ISSUE THREAD

**Issue by fastory** [jaywcjlove/hotkeys#35]
直接web使用不使用react的时候keyup事件的回调应该怎么设置，hotkey里面有针对每个键的keyup自定义事件处理吗？ thanks

**Comment by jaywcjlove** [comment]
@fastory 在React中使用，参考[react-hotkeys](https://github.com/jaywcjlove/react-hotkeys)

参考：https://github.com/jaywcjlove/react-hotkeys/blob/master/src/index.js#L30-L40

**Comment by jaywcjlove** [comment]
@fastory 你可以像这位同学一样写个扩展 

https://github.com/jaywcjlove/hotkeys/issues/26#issuecomment-408629192

**Comment by jaywcjlove** [comment]
@fastory  支持 keyup 事件玩儿法。更新 `hotkeys-js@3.6.1`

https://github.com/jaywcjlove/hotkeys/issues/57
