### ISSUE TITLE
Is there a way to programatically trigger a keybind?

### ISSUE THREAD

**Issue by manuelnogueiramov** [jaywcjlove/hotkeys#354]
@jaywcjlove great work with this library! :heart: 

I'm building an app where I have some keybinds (let's say `hotkeys("ctrl+shift+s")`) But I also have a button that allows me to do the same thing as this keybind. (Example below)

Let's say I have a "fileA" with this code:
```
export function doSomething(){
  console.log("This function really does something");
}
```

Then on fileB I have:

```
import { doSomething } from "fileA";

function App(){
  hotkeys("ctrl+shift+s", doSomething)
}
```

And on fileC:

```
import { doSomething } from "fileA";

<button onClick={doSomething}>Click me</button>
```

Instead of importing the final function in 2 places, I would prefer the to trigger the keybind on the button click;

fileC would look like this:

```
function triggerDoSomething(){
  hotkeys.trigger("ctrl+shift+s");
}
<button onClick={triggerDoSomething}>Click me</button>
```

**Comment by jaywcjlove** [comment]
```js
// Define shortcuts with a scope
hotkeys('ctrl+o, ctrl+alt+enter', 'issues', function(){
  console.log('do something');
});
hotkeys('o, enter', 'files', function(){ 
  console.log('do something else');
});

// Set the scope (only 'all' and 'issues' shortcuts will be honored)
hotkeys.setScope('issues'); // default scope is 'all'
```

`scope` may be the solution you need.

@manuelnogueiramov

**Comment by manuelnogueiramov** [comment]
Thank you for your response @jaywcjlove.
But I might have not been very good at explaining my question.

I need to trigger programatically the keybind.

On my button I need what ever this keybind has as a callback to be triggered on click (for instance)
```
function triggerDoSomething(){
  hotkeys.trigger("ctrl+shift+s");
}
<button onClick={triggerDoSomething}>Click me</button>
```

The function `triggedDoSomething` would trigger whatever callback the keybind **"ctrl+shift+s"** has.
Something along these lines: `hotkeys.trigger("ctrl+shift+s");`

**Comment by manuelnogueiramov** [comment]
I'm just wondering if there's an easy way to do this. I've looked at your tests that you mentioned here: https://github.com/jaywcjlove/hotkeys/issues/39#issuecomment-421803192

Something like this:
```
function __triggerKeyboardEvent(el, keyCode, opt) { 
   const eventObj = document.createEventObject ? 
     document.createEventObject() : document.createEvent('Events'); 
   if (eventObj.initEvent) { 
     eventObj.initEvent('keydown', true, true); 
   } 
   if (keyCode) { 
     eventObj.keyCode = keyCode; 
     eventObj.which = keyCode; 
   } 
   if (opt) { 
     for (const a in opt) { 
       if (Object.prototype.hasOwnProperty.call(opt, a)) { 
         eventObj[a] = opt[a]; 
       } 
     } 
   } 
   el.dispatchEvent ? el.dispatchEvent(eventObj) : el.fireEvent('onkeydown', eventObj); 
 } 
 ```
But within hotkeys, or at least, that would accept hotkeys nomenclature ("ctrl+shift+s")

**Comment by jaywcjlove** [comment]
This is a good idea. I added trigger method. Are you sure this is what you want?
@manuelnogueiramov 


```js
hotkeys.trigger('ctrl+o');
hotkeys.trigger('ctrl+o', 'scope2');
```

**Comment by manuelnogueiramov** [comment]
Much appreciated :)
