### ISSUE TITLE
Add support for passing useCapture to addEventListener

### ISSUE THREAD

**Issue by suhodolskiy** [jaywcjlove/hotkeys#367]
Is it possible to make the 3rd parameter([useCapture](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#syntax)) configurable for addEventListener? E.g. pass true instead of false. 
https://github.com/jaywcjlove/hotkeys/blob/18f2526115e29f095d4188ab04500cfde38c4372/src/utils.js#L3-L10

**Comment by jaywcjlove** [comment]
@suhodolskiy Welcome to submit PR 👍

**Comment by jaywcjlove** [comment]
@suhodolskiy thx! Upgrade `v3.9.3`
