### ISSUE TITLE
How I only set (command+r on mac) and (ctrl+r on mac)?

### ISSUE THREAD

**Issue by liu-xinhui** [jaywcjlove/hotkeys#390]
```javascript
hotkeys('ctrl+r, command+r', function() {
  alert('stopped reload!');
  return false;
});
```
If I use this, `ctrl+r, command+r` are all trigged on mac. I only want `command+r`

**Comment by xlboy** [comment]
Doesn't seem to support. You may be looking for something similar to the `mod` assistant in the [`mousetrap`](https://craig.is/killing/mice#api.bind) library.

Or you can manually determine the `MacOS/Windows` platform to register hotkeys

**Comment by liu-xinhui** [comment]
@xlboy thank you
