### ISSUE TITLE
不明白scope是指什么？

### ISSUE THREAD

**Issue by lxhao** [jaywcjlove/hotkeys#4]
相同的按键在不同区域按下时实现不同的操作，这段实在没懂，不明白你指的scope是什么意思，比如我想按下ctrl+r时在div1内执行刷新操作，在div2内执行退出操作,应该怎么实现？

**Comment by jaywcjlove** [comment]
比如：

你  a1 可以摁 “a”，“b”，“c” 三个键  
你  a2 可以摁 “a”，“b” 两个键  

a1 和 a2 就是一个区间范围。

当scope等于 a1 ，你摁 “a”键执行 某个事件evn1，  
当scope等于 a2 ，你摁 “a”键执行 某个事件evn2，  

摁同一个键执行不同的事件，我们只需要事先定义好不同的scope，通过 setScope 方法设置一下scope的值 `hotkeys.setScope('issues');` 

设定范围 

```js
// 一个快捷键，有可能干的活儿不一样哦
hotkeys('ctrl+o, ctrl+alt+enter', 'issues', function(){
    console.log('干点活儿');
});
hotkeys('o, enter', 'files', function(){ 
    console.log('另一种活儿');
});

// 设定范围scope 
hotkeys.setScope('issues'); // 默认所有事儿都干哦 
```

**Comment by lxhao** [comment]
谢谢解答！终于明白了！我之前理解成了这个快捷键可以对指定的部分标签生效。

**Comment by MerlinLmq** [comment]
这个scope实在是费解，坑了好大一波才发现这个答案。。。
