### ISSUE TITLE
How to call hotkeys() from within a loop?

### ISSUE THREAD

**Issue by regularlabs** [jaywcjlove/hotkeys#41]
I am trying to create hotkeys from an array of objects in javascript.

So I want to do something like:
```javascript
var shortcuts = [
	{'key': 'shift+alt+1', 'name': 'First'},
	{'key': 'shift+alt+2', 'name': 'Second'},
	{'key': 'shift+alt+3', 'name': 'Third'}
];

for (var i = 0; i < shortcuts.length; i++) {
	var shortcut = shortcuts[i];
	hotkeys(
		shortcut.key,
		function() {
			console.log(shortcut.name);
			return false;
		}
	)
}
```

But this does not work because of scopes and references and such, as the `shortcut` object will be the same for all call.
So hitting shift+alt+1, shift+alt+2 and shift+alt+3 will all place Third in the console log.

Can you tell me how I can get this so that console.log(shortcut.name); will output the correct name?

PS: I am aware this is not really a hotkeys specific question. More a general javascript thing.

**Comment by regularlabs** [comment]
To make the example easier:
```
var shortcuts = [
	{'key': 'shift+alt+1', 'name': 'First'},
	{'key': 'shift+alt+2', 'name': 'Second'},
	{'key': 'shift+alt+3', 'name': 'Third'}
];

for (var i = 0; i < shortcuts.length; i++) {
	var shortcut = shortcuts[i];
	hotkeys(
		shortcut.key,
		function() {
			console.log(shortcut.name);
			return false;
		}
	)
}
```

Hitting `shift+alt+1`, `shift+alt+2` and `shift+alt+3` will all place `Third` in the console log.
How can I get this so that `console.log(shortcut.name);` will output the correct name?

**Comment by regularlabs** [comment]
Ok, thanks.

Based on that, I come up with this:

```javascript
var shortcuts = [
	{'keys': ['shift+alt+1'], 'name': 'One'},
	{'keys': ['shift+alt+2'], 'name': 'Two'},
	{'keys': ['shift+alt+3', 'shift+alt+4'], 'name': 'Three & Four'}
];

var allKeys = [];

for (var i = 0; i < shortcuts.length; i++) {
	allKeys = allKeys.concat(shortcuts[i].keys);
}

allKeys = allKeys.join(',');

hotkeys(allKeys, function(event, handler) {
	for (var i = 0; i < shortcuts.length; i++) {
		var shortcut = shortcuts[i];

		if (shortcut.keys.indexOf(handler.key) > -1) {
			console.log(shortcut.name);
		}
	}
});
```

**Comment by astorm** [comment]
At the risk of restarting a party that's already ended, you could also do something like this.

    var shortcuts = [
        {'key': 'shift+alt+1', 'name': 'First'},
        {'key': 'shift+alt+2', 'name': 'Second'},
        {'key': 'shift+alt+3', 'name': 'Third'}
    ];

    var hotkeys_with_shortcut = function(shortcut, callback) {
        hotkeys(shortcut.key, function() {
            console.log(shortcut.name);
            return false;
        });
    }


    for (var i = 0; i < shortcuts.length; i++) {
        hotkeys_with_shortcut(shortcuts[i]);
    }
    
From a "modern javascript" point of view, the problem was you were defining the `shortcut` variable in one function, and then using it in an inner-function (this inner function is often called a closure).  Javascript will remember the value of `shortcut` when the `hotkeys` eventually calls your javascript.  Since `hotkeys` calls your function after your loop has run, `shortcut` has the value from your last time through the loop.  

Since javascript only has global and functional scope, the solution to most scope problems (like the one above) is to introduce a new function.  The `hotkeys_with_shortcut` function above only ever knows about the `shortcut` you pass in.

**Comment by regularlabs** [comment]
Yeah, thanks. Thinking about it, this was way simpler than I though.
As I am using an object with methods anyway, I just created an extra method.
Something like:
```javascript
var shortcuts = [
    {'key': 'shift+alt+1', 'name': 'First'},
    {'key': 'shift+alt+2', 'name': 'Second'},
    {'key': 'shift+alt+3', 'name': 'Third'}
];

myShortcuts.createHotkeys(shortcuts);

var myShortcuts = {
	createHotkeys: function(shortcuts) {
		for (var i = 0; i < shortcuts.length; i++) {
			this.createHotkey(shortcuts[i]);
		}
	},

	createHotkey: function(shortcut) {
		hotkeys(shortcut.key, function() {
			console.log(shortcut.name);
			return false;
		});
	},
}
```
