### ISSUE TITLE
[feature request] unbind 指定的 handler 而不是一下子解绑所有的

### ISSUE THREAD

**Issue by JounQin** [jaywcjlove/hotkeys#44]
As title.

**Comment by jaywcjlove** [comment]
@JounQin 事实上你可以通过 `Scope` 来控制。

**Comment by JounQin** [comment]
@jaywcjlove scope 一次只能生效一个 scope + 'all' 吧？

**Comment by jaywcjlove** [comment]
@JounQin 你可以在代码执行的时候 随意切换 `scope`

**Comment by JounQin** [comment]
比如在页面里有很多子模块，他们可能对同一个按键组合同时做监听，子模块卸载的时候要把对应的监听 unbind，切 scope 不能使监听同时生效啊。

**Comment by jaywcjlove** [comment]
@JounQin  你这样，不能把快捷键写到单独的 component 里面去，监听事件绑定到 document 上，如果放到单独的 component 里面，对其它 component 里面的快捷键没有办法控制。

如果不绑定到 document 上，绑定到对应的 component 根节点上，会导致，部分区域获得焦点才能触发事件

解决办法： 根组件， 使用 `hotkey.js` 通过全局状态 `通知` 执行事件。

**Comment by JounQin** [comment]
我只是说明一种情景，每个子模块都可能是不同人维护的，其他组件想监听相同的快捷键，用一个监听全局通知当然是好的，但是为什么不能像 jQuery 对 document 可以监听多次，也可以单独取消某个特定的监听器一样呢？

**Comment by jaywcjlove** [comment]
keymaster 这种方式也可以，我回头给加上去
