### ISSUE TITLE
💡：我有个想法，想用函数式组件重构一遍，是否可行？

### ISSUE THREAD

**Issue by LonelyFellas** [jaywcjlove/hotkeys#483]

**Comment by jaywcjlove** [comment]
@LonelyFellas 这个库维护超过 9 年，光 npm 下载 超过 2000万，会合并来自社区的小修小改，不会大改动，我个人 2021 就失去了大改造的动力，如果你有兴趣可以起个仓库实现自己的想法，这个对自己技术提升非常有帮助

- https://github.com/jaywcjlove/hotkeys-js/issues/313

**Comment by jaywcjlove** [comment]
@LonelyFellas 有想法是非常棒的，当初启动这个库的时候，有个 [keymaster](https://github.com/madrobby/keymaster) 的库并没有在 npm 上提交，然后自己有一些想法，显然人家已经不维护了，我就自己起了一个仓库，做起来了

- https://github.com/jaywcjlove/hotkeys-js/issues/126

**Comment by jaywcjlove** [comment]
- https://github.com/madrobby/keymaster/issues/181
