### ISSUE TITLE
isPressed('ctrl') only works at least one 'ctrl' listener

### ISSUE THREAD

**Issue by rico345100** [jaywcjlove/hotkeys#49]
If there's no ctrl listener, this always return false even I pressed ctrl:

```javascript
this.debugTimer = setInterval(() => {
  console.log(hotkeys.isPressed('ctrl'));    // Always false
}, 300);
```

However when I just add this dummy listener, now it works.

```javascript
this.debugTimer = setInterval(() => {
  console.log(hotkeys.isPressed('ctrl'));
}, 300);

hotkeys('ctrl', () => {});
```

However I tried with command key, not works regardless there's a listener or not. Possibly it's bug.

Tested with Chrome@71.0.3578.98, Hotkeys@3.4.1.

**Comment by jaywcjlove** [comment]
@rico345100 Put it in the callback function.

```js
hotkeys('a', function(){
  console.log(hotkeys.isPressed("a")); //=> true
  console.log(hotkeys.isPressed("A")); //=> true
  console.log(hotkeys.isPressed(65)); //=> true
});
```

**Comment by rico345100** [comment]
@jaywcjlove Thank you for quick response! I just realized that this module built for easy "hot key" management, so should be your suggestion is right way.

However just one more question, I didn't attached any "cmd" listener but "hotkeys.isPressed('cmd')" worked. Isn't it supposed to be not work?

**Comment by rico345100** [comment]
@jaywcjlove Ok then. I was looking for library that handles cross browsing + cmd/ctrl keyboard events, and this isn't what I expected. However this module nice and cool, could be useful in some cases, definitely I will use some day. You can close this. Again, thanks for quick response.
