### ISSUE TITLE
Unbind with Method after multiple Binds

### ISSUE THREAD

**Issue by spencer516** [jaywcjlove/hotkeys#53]
Hi! 

There seems to be a small bug in how `unbind` works. Take this scenario:

```js
const methodA = () => console.log('hello from a!');
const methodB = () => console.log('hello from b!');

hotkeys('shift+a', methodA);
hotkeys('shift+b', methodB);

hotkeys.unbind('shift+a', methodA);
hotkeys.unbind('shift+b', methodB);
```

I would expect that both the `shift+a` and `shift+b` shortcuts would no longer be listening to events. However, the `shift+a` method still fires. 

This is because when the first [potential matching handler is found](https://github.com/jaywcjlove/hotkeys/blob/master/src/main.js#L110), the method is returned — cutting short the loop (so none of the other handler objects are checked). 

That line should be replaced with: 

```js
if (method && obj.method !== method) break;
```

I'll open a PR in a minute to address.

**Comment by jaywcjlove** [comment]
@spencer516 👍 

I look forward to your opening PR.
