### ISSUE TITLE
keyup and keydown don't exist in typings file

### ISSUE THREAD

**Issue by JohannesKlauss** [jaywcjlove/hotkeys#59]
The new `keyup` and `keydown` feature are missing in the Option Interface in the typings file, or am I missing something?

**Comment by jaywcjlove** [comment]
??? @JohannesKlauss

**Comment by JohannesKlauss** [comment]
You can do something like this:
```
hotkeys('ctrl+a,alt+a+s', { keyup: true }, (evn, handler) => {
  // ....
});
```

But the `{keyup: boolean}` part is nowhere declared inside the declaration file for Typescript.

**Comment by jaywcjlove** [comment]
@JohannesKlauss thx!
