### ISSUE TITLE
Direction key can not clear correctly

### ISSUE THREAD

**Issue by yantze** [jaywcjlove/hotkeys#60]
Hi, I defined a shortcut: 
```
hotkeys('ctrl+j', (e,handler) => {
   // do something.
})
```
Here is the environment:

https://output.jsbin.com/sifecut  

Steps:
Press `Command+Shift+Left`, then release all key except `Command`, then press `Ctrl`, release `Command` and press `j`.

Result:
The page will not display shortcuts.

Reason:
`Command+Shift+Left` keyup not trigger `e.keyCode === 37` event.

PS: Because of In electron environment, Simple press Command+shift+left then press Command+L, do something is easy.

**Comment by jaywcjlove** [comment]
@yantze This combination keyboard is currently not supported.

**Comment by yantze** [comment]
Ok, thanks for the reply
