### ISSUE TITLE
Cannot use hotkeys if input in focused

### ISSUE THREAD

**Issue by wenwen1995** [jaywcjlove/hotkeys#62]
if i have an input focused I can't seem to get any hotkeys to work ... But  when I click other place,the input loses focus,it can work again.I tried this way,

```js
 hotkeys('f5', function(event, handler){
  event.preventDefault() 
  document.activeElement.blur();
});
```
but it seems no use....

**Comment by mak1A4** [comment]
This issue was closed a long time ago, but how did you fix your problem? I have exactly the same issue ...

**Comment by drinkmaker** [comment]
> 

Here https://github.com/jaywcjlove/hotkeys-js/issues/64

**Comment by wenwen1995** [comment]
您好，您的邮件我已收到，如果未能及时回复敬请谅解！
