### ISSUE TITLE
when user focus input field hotkeys are not available

### ISSUE THREAD

**Issue by TammyCT** [jaywcjlove/hotkeys#64]
I know this is by design,

but can you set a trigger to let user can use hotkey when the input field is in focus?

**Comment by jaywcjlove** [comment]
@TammyCT Can this be achieved?

```js
hotkeys.filter = function(event){
  return true;
}
//How to add the filter to edit labels. <div contentEditable="true"></div>
//"contentEditable" Older browsers that do not support drops
hotkeys.filter = function(event) {
  var tagName = (event.target || event.srcElement).tagName;
  return !(tagName.isContentEditable || tagName == 'INPUT' || tagName == 'SELECT' || tagName == 'TEXTAREA');
}

hotkeys.filter = function(event){
  var tagName = (event.target || event.srcElement).tagName;
  hotkeys.setScope(/^(INPUT|TEXTAREA|SELECT)$/.test(tagName) ? 'input' : 'other');
  return true;
}
```

**Comment by TammyCT** [comment]
> @TammyCT Can this be achieved?
> 
> ```js
> hotkeys.filter = function(event){
>   return true;
> }
> //How to add the filter to edit labels. <div contentEditable="true"></div>
> //"contentEditable" Older browsers that do not support drops
> hotkeys.filter = function(event) {
>   var tagName = (event.target || event.srcElement).tagName;
>   return !(tagName.isContentEditable || tagName == 'INPUT' || tagName == 'SELECT' || tagName == 'TEXTAREA');
> }
> 
> hotkeys.filter = function(event){
>   var tagName = (event.target || event.srcElement).tagName;
>   hotkeys.setScope(/^(INPUT|TEXTAREA|SELECT)$/.test(tagName) ? 'input' : 'other');
>   return true;
> }
> ```

Thx, the problem can be solved by this.
