### ISSUE TITLE
会污染全局变量

### ISSUE THREAD

**Issue by HR-Alan** [jaywcjlove/hotkeys#7]
建议把整个源码都用匿名函数包起来，这样子暴露会污染全局变量的，具体方法参考JQuery或者underscore.js的做法

**Comment by jaywcjlove** [comment]
@HR-Alan 

https://github.com/jaywcjlove/hotkeys/blob/master/dist/hotkeys.js

**Comment by jaywcjlove** [comment]
编译后的有你说的东西。

**Comment by HR-Alan** [comment]
OK
