### ISSUE TITLE
event.preventDefault() 无法屏蔽窗体原生的热键？

### ISSUE THREAD

**Issue by konwww** [jaywcjlove/hotkeys#71]
```js
hotkeys('ctrl+e,ctrl+b,alt+space,f', function (event, handler) {
    event.preventDefault();
    switch (handler.key) {
        case "ctrl+e":
            console.log("pressed ctrl+e");
            insertAtCursor(text, "<center></center>");
            break;
        case "ctrl+b":
            insertAtCursor(text, "<strong></strong>");
            break;
        case "alt+space":
            insertAtCursor(text, "&nbsp;&nbsp;&nbsp;&nbsp;");
            break;
        case "f":
            console.log("f");
            break;

})
```
我是这样用的，如果执行了alt+space后就无法再次使用快捷键，之前被屏蔽掉的原生的触发事件也会再次出现，版本是3.6.4

**Comment by jaywcjlove** [comment]
@konwww 我测试了一下，可以屏蔽原生浏览器快捷键。 [官网](https://git.io/hotkeys.js) `command+r` 原本是刷新页面，屏蔽之后就不起作用了。

**Comment by jaywcjlove** [comment]
@konwww 有些键是屏蔽不了的。

**Comment by konwww** [comment]
> @konwww 有些键是屏蔽不了的。

我知道，我这里遇到的问题是alt+space后就无法执行我定义的快捷键了，然后整个对原生快捷键的屏蔽也全都失效了，而且控制台也没有报错，找了很久也没找到解决办法

**Comment by jaywcjlove** [comment]
`alt+space` `alt` 加`空格`键? 我这里没有办法测试诶，在Mac上是个切换输入法的键。我试一试。

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/57313510-588d6900-7122-11e9-9e15-c8d417c771b8.png)

```js
hotkeys('ctrl+a,ctrl+b,r,alt+space', (event, handler) => {
  event.preventDefault();
  if (handler.key === 'ctrl+a') console.log('you pressed ctrl+a!');
  if (handler.key === 'ctrl+b') console.log('you pressed ctrl+b!');
  if (handler.key === 'r') console.log('you pressed r!');
  if (handler.key === 'alt+space') console.log('you pressed alt+space!');
});
```

@konwww 本地测试没毛病诶

**Comment by konwww** [comment]
我刚又试了一下，是在按下alt+space后整个快捷键都是有效的，其余快捷键也可以正常工作，但是如果在按下alt+space后手动去关闭了左上角弹出的那个窗体菜单，那么所有的快捷键都会失效，然后屏蔽也会失效。我想是不是生命周期出了问题？技术太垃圾了，自己找不到问题

**Comment by jaywcjlove** [comment]
@konwww 你的焦点已经不在 web 页面上了，当然全部失效了。

**Comment by konwww** [comment]
> @konwww 你的焦点已经不在 web 页面上了，当然全部失效了。

那这是不是无解了？在这之后不管我对页面做啥操作，这个快捷键都不会生效了？

**Comment by jaywcjlove** [comment]
@konwww 重新点击页面即可就可重新回到焦点，快捷键继续可以操作的，我这里测试是成功的。

我不知道你是什么浏览器，代码是怎样写得。可否 codepen 来个实例， 告诉我测试浏览器的版本？

**Comment by konwww** [comment]
![image](https://user-images.githubusercontent.com/34157376/57315468-3a296c80-7126-11e9-8a66-e288d4df441e.png)
![Uploading image.png…]()
两个浏览器都有同样的情况，重新定位在页面上也不能解决问题，我用的是这个
`    <script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>
`
下面就是相关的js
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script src="https://cdn.bootcss.com/showdown/1.9.0/showdown.min.js"></script>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js">
    </script>
    <script src="https://cdn.staticfile.org/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    
    <script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>
    <script>
        hotkeys.filter = function (event) {
            return true;
        };
        hotkeys('ctrl+e,ctrl+b,tab,f', function (event, handler) {
            event.preventDefault();
            switch (handler.key) {
                case "ctrl+e":
                    console.log("pressed ctrl+e");
                    insertAtCursor(text, "<center></center>");
                    break;
                case "ctrl+b":
                    insertAtCursor(text, "<strong></strong>");
                    break;
                case "tab":
                    insertAtCursor(text, "&nbsp;&nbsp;&nbsp;&nbsp;");
                    break;
                case "f":
                    console.log("f");
                    break;
            }
        });
    </script>

<script type="text/javascript">
    var text = document.getElementById('text');
    var insert = document.getElementById('insert');
    insert.onclick = function () {
        insertAtCursor(text, this.value);
    };

    function insertText(index) {
        let value = $.cookie(index);
        insertAtCursor(text, value);
        compile();
    }

    function insertAtCursor(myField, myValue) {
        if (document.selection) {
            //IE support
            myField.focus();
            sel = document.selection.createRange();
            sel.text = myValue;
            sel.select();
        } else if (myField.selectionStart || myField.selectionStart === '0') {
            //MOZILLA/NETSCAPE support
            var startPos = myField.selectionStart;
            var endPos = myField.selectionEnd;
            var beforeValue = myField.value.substring(0, startPos);
            var afterValue = myField.value.substring(endPos, myField.value.length);

            myField.value = beforeValue + myValue + afterValue;

            myField.selectionStart = startPos + myValue.length;
            myField.selectionEnd = startPos + myValue.length;
            myField.focus();
        } else {
            myField.value += myValue;
            myField.focus();
        }
    }
</script>

`

**Comment by konwww** [comment]
浏览器都是新版的chrome和firefox，而且都是同样的问题

**Comment by jaywcjlove** [comment]
@konwww 我用实例测试了没有任何毛病，实例：https://codepen.io/jaywcjlove/pen/RmPLLV

**Comment by konwww** [comment]
那应该就是我自己的问题了，很迷，我再自己找找问题吧，很晚了大佬早点睡
