### ISSUE TITLE
bug: caps_lock 

### ISSUE THREAD

**Issue by yyjjqq94** [jaywcjlove/hotkeys#77]
https://stackoverflow.com/questions/39016292/keydown-event-is-not-fired-for-capslock-in-mac
Chrome treats the CAPS ON as keydown because it treats the on/off as press and hold

**Comment by jaywcjlove** [comment]
@yyjjqq94 It seems that there is no problem.  https://codepen.io/jaywcjlove/pen/JqWMdw

**Comment by yyjjqq94** [comment]
mac + chrome
![image](https://user-images.githubusercontent.com/26669481/57827605-83d71e80-77da-11e9-9a76-28c6e06dfeff.png)

**Comment by yyjjqq94** [comment]
mac + safari
![image](https://user-images.githubusercontent.com/26669481/57827773-52ab1e00-77db-11e9-8b5f-d650386f8dac.png)

**Comment by yyjjqq94** [comment]
mac + firefox
![image](https://user-images.githubusercontent.com/26669481/57827886-cea56600-77db-11e9-9294-a328acd2ed78.png)

**Comment by yyjjqq94** [comment]
'tab'  has problem too , but it's behavior is different from ‘capslock'

**Comment by yyjjqq94** [comment]
if press 'tab' to location bar , only  execute 'keydown' event

**Comment by jaywcjlove** [comment]
@yyjjqq94 Event triggering is associated with settings.

![image](https://user-images.githubusercontent.com/1680273/57829432-812bf780-77e1-11e9-8df7-cfb1c9d8d869.png)

![image](https://user-images.githubusercontent.com/1680273/57829555-ebdd3300-77e1-11e9-8e4e-80c2a1c07f74.png)

```js
hotkeys('capslock,tab', { keyup: true, keydown: true }, (evn, handler) => {
  evn.preventDefault();
  console.log('~~~~~~~:evn.type', evn.type, handler.key);
  if (evn.type === 'keydown') {
    console.log('~~~~~~~:keydown:', evn.type, handler);
  }
  if (evn.type === 'keyup') {
    console.log('~~~~~~~:keyup:', evn.type, handler);
  }
});
```

**Comment by jaywcjlove** [comment]
@yyjjqq94 Use `evn.preventDefault();` to prevent jumps to the address bar.

**Comment by yyjjqq94** [comment]
thanks, but in my opinion, 'capslock, tab' should not record in _downKeys. those key have their default meaning,

**Comment by yyjjqq94** [comment]
like 'capslock', if user don't know the setting, they will think it is program's bug

**Comment by jaywcjlove** [comment]
@yyjjqq94 Studyed for a long time, there is no good way.
