### ISSUE TITLE
unbind 在某些场景下无法正确解绑事件

### ISSUE THREAD

**Issue by CodeDaraW** [jaywcjlove/hotkeys#81]
参考 [JSBin](https://jsbin.com/pojiwuh/1/edit?html,console,output)：
``` js
hotkeys('shift+a,a', (event, handler) => {
  const handlerKey = handler.key;
  console.log(handlerKey);
});
```
此时 `hotkeys.unbind('shift+a,a')` 只能解绑 `shift+a` 的事件，无法解绑 `a` 的事件，只有 `hotkeys.unbind('a,shift+a')` 才能正确解绑 `shift+a` 和 `a` 的事件。  

使用 `hotkeys.unbind('shift+a,a')` 的问题：在 `unbind` 函数中，解绑 `shift+a` 时 `mods` 数组不为空；在解绑 `a` 时 `mods` 应该重新置空，否则影响下面的判断。

**Comment by jaywcjlove** [comment]
@CodeDaraW thx!

**Comment by jaywcjlove** [comment]
@CodeDaraW  Upgrade `+ hotkeys-js@3.6.9`
