### ISSUE TITLE
[BUG]All Hotkeys not work sometimes

### ISSUE THREAD

**Issue by Minoyu** [jaywcjlove/hotkeys#86]
If we press F6 in Chrome and click on the page again, all shortcuts will not work.

如果页面按动了一些浏览器内置的快捷键例如F6使页面失去焦点后，就算再次点击页面所有的快捷键也依然不会生效,不知为何原因但挺影响体验的。

求助:(

**Comment by jaywcjlove** [comment]
@Minoyu 测试没有问题，不知道你代码怎么写的 ，https://codepen.io/ 来个实例？

**Comment by Minoyu** [comment]
项目有些复杂 不过我在这个issue下贴的demo样例中发现了同样的问题 https://github.com/jaywcjlove/hotkeys/issues/42
https://codepen.io/macchie/pen/dQGpNa/
一旦焦点不是因为鼠标点击原因出的页面，就再也没法点回来了 包括很多 如F6 ctrl+f等等等等

**Comment by Minoyu** [comment]
Chrome v73

**Comment by jaywcjlove** [comment]
@Minoyu 找到问题所在，已解决，升级 `+ hotkeys-js@3.6.11`

**Comment by jaywcjlove** [comment]
@Minoyu https://codepen.io/jaywcjlove/pen/oRyMmM 新实例

**Comment by Minoyu** [comment]
@jaywcjlove 非常感谢 好像我又发现了一个新问题，不过不清楚是不是库的bug，我开个新issue和大佬请教下吧

**Comment by jaywcjlove** [comment]
@Minoyu 👌

**Comment by yuwengCipher** [comment]
> @Minoyu 找到问题所在，已解决，升级 `+ hotkeys-js@3.6.11`

只有 button 元素才能响应事件回调吗？换成其他元素如 div，则回调事件不会触发

**Comment by yuwengCipher** [comment]
> @Minoyu https://codepen.io/jaywcjlove/pen/oRyMmM 新实例

只有 button 元素才能响应事件回调吗？换成其他元素如 div，则回调事件不会触发
