### ISSUE TITLE
Numpad keys not detected

### ISSUE THREAD

**Issue by swd120** [jaywcjlove/hotkeys#89]
Numpad keys are not detected with normal handlers (they can be detected under the '*' handler, but not under a regular handler)

Demo:
https://jsfiddle.net/fk1o32a9/7/

Actual:
Using Digit1, event is detected for both events (both 1 and \*)
Using Numpad1, event is detected only for "*" event

Expected:
Using Digit1, event is detected for both events (both 1 and *)
Using Numpad1, event is detected for both events (both 1 and *)

**Comment by jaywcjlove** [comment]
@swd120 I need to buy a keyboard.

**Comment by swd120** [comment]
Let me know if there's any additional info you might need.

**Comment by bichotll** [comment]
It works for me (mac).
@swd120 No offense - you sure that the keypad num is enabled?

**Comment by pablocar80** [comment]
@bichotll I was able to reproduce the issue with my keypad turned on and numlock off. It's like the library believes that the `'1'` from the keypad was a different key. The key does get captured under `'*'` but not under `'1'`.

**Comment by pascalrogalla** [comment]
It seems to be a Windows issue.
Works fine on MAC.
Maybe because the `KeyboardEvent.which` is different between Mac and Windows.

That's my current Workaround:
```
hotkeys('*', ({key}) => {
   const keyValue = parseInt(key, 10)
   if(keyValue){
      doSth(keyValue)
   }
})
```

**Comment by ishan576** [comment]
Yes, the issue is with windows. Does anyone have any solution?

**Comment by CourtHive** [comment]
I'm using react-hotkeys-hook ... @ishan576 are you suggesting that `var.js` needs to be modified and then build?  I would then need to do a custom build of react-hotkeys-hook as well?

@jaywcjlove this looks pretty straightforward... any chance you could make the fix?

**Comment by ishan576** [comment]
> I'm using react-hotkeys-hook ... @ishan576 are you suggesting that `var.js` needs to be modified and then build?  I would then need to do a custom build of react-hotkeys-hook as well?
> 
> @jaywcjlove this looks pretty straightforward... any chance you could make the fix?

@CourtHive: My usage was in a pure js mode. But yes, I think you'll have to modify and re-build.

**Comment by CourtHive** [comment]
thanks @ishan576 appreciate the reply

**Comment by gimoteco** [comment]
Same problem happening with me, trying to debug I noticed that only it only happen on Firefox on Chrome works fine. I'm using the react wrapper `react-hotkeys-hook` but the same problem happens in this lib's homepage.

**Comment by CourtHive** [comment]
@gimoteco are you saying that the numeric keys work for you on Chrome?  We have tested in Chrome on Windows and it does not work.  Based on @ishan576 comments above and looking at the code I don't think the key codes for numeric keypad are handled at all.  I don't understand why this issue can't be addressed as the solution seems to be fairly straightforward...

**Comment by gimoteco** [comment]
Yeah, testing in https://wangchujiang.com/hotkeys/ the numpad keys work on chrome and don't work on firefox (just the numpad digit keys). 
I'm using MacOS 10.15.6, Firefox 80 and Chrome Version 85.0.4183.83 (Official Build) (64-bit)
