### ISSUE TITLE
on mac press shift+option+f error 

### ISSUE THREAD

**Issue by zuoliang0** [jaywcjlove/hotkeys#99]
when press `shift+option+f ` on mac will Identification with `Ï` i don't kown how to fix that.

thank you.

**Comment by jaywcjlove** [comment]
@zuoliang0 There is an example here without any problems: 

https://codepen.io/jaywcjlove/pen/eqBabm

**Comment by zuoliang0** [comment]
yes,that's ok,but why 
![image](https://user-images.githubusercontent.com/8434253/62095603-81ea0b00-b2b3-11e9-9a66-56420421bb52.png)
https://codepen.io/zuoliang0/pen/JgWbGq

**Comment by jaywcjlove** [comment]
@zuoliang0 You can review your code carefully.

**Comment by zuoliang0** [comment]
no.. i don't understand what happen .
![image](https://user-images.githubusercontent.com/8434253/62096012-cde97f80-b2b4-11e9-9003-0a7956260318.png)
could you tell me how to fix that ?

**Comment by jaywcjlove** [comment]
@zuoliang0 

![image](https://user-images.githubusercontent.com/1680273/62096254-97603480-b2b5-11e9-998b-77b23dcba90c.png)

I don't know your operation. I don't know how to write your code. There is no way to help you.

**Comment by zuoliang0** [comment]
you just press alt ？

when you press 3 key alt ,shift ,f then you can see that.

I want use this tools to catch use press , and set to them hot keys.

**Comment by zuoliang0** [comment]
if you busy for work ,i'm so sorry for  disturb you .
